### ISSUE TITLE
Timeout behavior is not the same as pexpect

### ISSUE THREAD

**Issue by yancyribbens** [rust-cli/rexpect#122]
pexpect will eventually raise a timeout: 

> If nothing matches an expected pattern then [expect()](https://pexpect.readthedocs.io/en/stable/api/pexpect.html#pexpect.spawn.expect) will eventually raise a [TIMEOUT](https://pexpect.readthedocs.io/en/stable/api/pexpect.html#pexpect.TIMEOUT) exception. The default time is 30 seconds, but you can change this by passing a timeout argument to [expect()](https://pexpect.readthedocs.io/en/stable/api/pexpect.html#pexpect.spawn.expect):

It looks like rexpect does not timeout but hangs forever.

**Comment by yancyribbens** [comment]
Is there a way to make rexpect timeout in some way like pexpect?

**Comment by d4h0** [comment]
@yancyribbens: From [the docs of `spawn`](https://docs.rs/rexpect/0.5.0/rexpect/session/fn.spawn.html):

> `timeout`: If Some: all `exp_*` commands time out after x milliseconds, if None: never times out. It’s highly recommended to put a timeout there, as otherwise in case of a problem the program just hangs instead of exiting with an error message indicating where it stopped. For automation 30’000 (30s, the default in pexpect) is a good value.

**Comment by yancyribbens** [comment]
that works
