### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by kayagokalp** [rust-cli/rexpect#126]
Hey I came here to check if there is an effort to update nix version. Last release seems to be done 2 years ago and not much activity in the comments. Is it safe to assume this is unmaintained at this point/is the work group not active anymore? I am happy to help maintain/fork if that is the case. We are heavily using this nice crate for cli testing.

**Comment by epage** [comment]
@matthiasbeyer whats your status with this repo?  I've mostly been ignoring it since you were taking the lead.

**Comment by matthiasbeyer** [comment]
@epage feel free to take over completely, I do not have enough time for this, sorry.

**Comment by epage** [comment]
@matthiasbeyer can you run `cargo owner --add github:rust-cli:Maintainers`

**Comment by matthiasbeyer** [comment]
`Owner team github:rust-cli:maintainers has been added as an owner of crate rexpect`

:heavy_check_mark:
