### ISSUE TITLE
Moving repository to CLI-WG org?

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-cli/rexpect#71]
Hi!

In the last meetup of the CLI WG it came up that we want to make this crate to the CLI WG org.

The benefits that we would get from that would be the increased bus factor. I know we have three or four people that currently maintain this crate, and we wouldn't even increase that number any further when moving to the CLI WG org, but we would get the option of the WG having access to the repository settings and if it happens that we (the current maintainers) are _all_ unresponsive, the WG can install new maintainers.

Please lets have a discussion about that.

@petreeftime suggested that after the maintainership thing got cleared up, we can talk about moving to a more permanent place (https://github.com/philippkeller/rexpect/issues/43#issuecomment-1242927575) ... and that's what I'm trying here now! :laughing: 
@souze is also a maintainer IIRC and of course
@philippkeller has the final say as the owner of the repository!

**Comment by souze** [comment]
Sounds good to me. But off course, up to @philippkeller :)

**Comment by philippkeller** [comment]
Guys, I'm so happy that this little project of mine gets a proper home and lives its independent live in a proper "organization" - I'm all for moving! Maybe you could mention me somewhere as the starter of the project?

How would such a moving be accomplished? Would you fork the project and then we would reduce this repo to only the README page pointing to the new location?

**Comment by matthiasbeyer** [comment]
> Maybe you could mention me somewhere as the starter of the project?

Definitively!

> How would such a moving be accomplished? Would you fork the project and then we would reduce this repo to only the README page pointing to the new location?

No, there's a github functionality named "Transfer ownership" or something like that. That has the additional benefit that links to https://github.com/philippkeller/rexpect/ automatically get rerouted to that new location, which is _really_ neat!

What you would do is: Transfer ownership to https://github.com/rust-cli. @epage will then accept this and that's all that needs to be done on your side as far as I can see.

Maybe @epage knows some more details and where that actual button is? :laughing:

Lets hear what @petreeftime has to add to this topic and whether they're on board!
Lets wait for response from @epage and then set a date for moving if @petreeftime also agrees! :wink:

**Comment by epage** [comment]
Under "Settings", scroll down to the bottom in the "Danger Zone" is a "Transfer" button.

**Comment by petreeftime** [comment]
Sounds good to me!

**Comment by matthiasbeyer** [comment]
Okay, so it seems that everyone is on board! I think you can go ahead, @philippkeller :tada:

**Comment by philippkeller** [comment]
I tried to transfer the ownership to `https://github.com/rust-cli` but I get the error `Cannot find new owner 'https://github.com/rust-cli'` - anyone has any idea how to solve this?

**Comment by epage** [comment]
Sent you an invite

**Comment by philippkeller** [comment]
and done, I'm writing this comment now from https://github.com/rust-cli/rexpect/issues/71 🎉

**Comment by matthiasbeyer** [comment]
:tada: awesome yall! I am taking the liberty of closing this issue then! :+1:
