### ISSUE TITLE
Update on crates.io 

### ISSUE THREAD

**Issue by petreeftime** [rust-cli/rexpect#77]
There were quite a few changes since version v0.4.0, it would be a good idea to push a new version out to crates.io.

Are there any guidelines for rust-cli organization on how it's best to do this, for example changelog format, steps, etc?

**Comment by matthiasbeyer** [comment]
So the majority of the rust-cli people use `cargo-release`. It is not mandatory though. If you want, you can do something else.

Either way, it is strongly recommended that we _document_ how the release process looks like.

**Comment by petreeftime** [comment]
@matthiasbeyer I don't seem to have ownership on crates.io, so I can't publish. When you have time, go ahead.

**Comment by petreeftime** [comment]
Release is here: https://github.com/rust-cli/rexpect/releases/tag/v0.5.0

**Comment by matthiasbeyer** [comment]
Release published.

You don't have access because rust-bus was added to the owners, but not rust-cli, I guess.

Either way, you just got an invite.
