### ISSUE TITLE
bash_read.rs: use rexpect::error::Error;  --> could not find `error` in `rexpect`

### ISSUE THREAD

**Issue by tjyang** [rust-cli/rexpect#81]
I am learning rexpect via *.rs in examples dir.
- With following Cargo.toml and needed directory layout, I was able to run command like "cargo run --bin bash_read" to see if it works.

<details>

[me@ipa01 examples]$ cat Cargo.toml
[package]
name = "rexpect-examples"
version = "0.1.0"
authors = ["rexpect authors"]
description = "Cargo.toml to compile rexpect examples in batch"
license     = "MIT"
homepage    = "https://github.com/rust-cli/rexpect"
readme      = "README.md"
categories  = ["command-line-utilities" ]
keywords    = ["rexpect", "rust", "bash"]

[dependencies]
rexpect = "0.4.0"
[me@ipa01 examples]$

[me@ipa01 examples]$ tree -L 23
.
├── Cargo.lock
├── Cargo.toml
└── src
    └── bin
        └── bash_read.rs

2 directories, 3 files
[me@ipa01 examples]$

</details>

- Output of "cargo run --bin bash_read" command

<details>

 [me@ipa01 examples]$ cargo run --bin bash_read
   Compiling memchr v2.5.0
   Compiling libc v0.2.135
   Compiling cc v1.0.73
   Compiling gimli v0.26.2
   Compiling version_check v0.9.4
   Compiling adler v1.0.2
   Compiling cfg-if v1.0.0
   Compiling nix v0.14.1
   Compiling rustc-demangle v0.1.21
   Compiling fastrand v1.8.0
   Compiling remove_dir_all v0.5.3
   Compiling regex-syntax v0.6.27
   Compiling void v1.0.2
   Compiling cfg-if v0.1.10
   Compiling bitflags v1.3.2
   Compiling miniz_oxide v0.5.4
   Compiling error-chain v0.12.4
   Compiling backtrace v0.3.66
   Compiling object v0.29.0
   Compiling aho-corasick v0.7.19
   Compiling addr2line v0.17.0
   Compiling tempfile v3.3.0
   Compiling regex v1.6.0
   Compiling rexpect v0.4.0
   Compiling rexpect-examples v0.1.0 (/home/me/github/rexpect/contrib/examples)
error[E0432]: unresolved import `rexpect::error`
 --> src/bin/bash_read.rs:2:14
  |
2 | use rexpect::error::Error;
  |              ^^^^^ could not find `error` in `rexpect`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `rexpect-examples` due to previous error
[me@ipa01 examples]$

</details>

-  src/bin/bash_read.rs is unchanged examples/bash_read.rs.

**Comment by matthiasbeyer** [comment]
Yes, in `0.4.0` [that module is called `errors`](https://docs.rs/rexpect/latest/rexpect/errors/index.html)

**Comment by tjyang** [comment]
Or  there should be  a examples/0.4.0/*.rs ?

**Comment by matthiasbeyer** [comment]
I don't understand why you're thinking that the examples need fixing?

**Comment by tjyang** [comment]
Because examples/*.rs using new rexpect::error name while 0.4.0 we can download from crates.io is using rexpect:errors.
more learning trouble for beginner like me.

**Comment by matthiasbeyer** [comment]
There is no point in renaming the module on latest master. This would actually break our build! If you want to look at source to understand how a crate is working, you should look at the version you're using, in your case `0.4.0`, and not latest master!

**Comment by tjyang** [comment]
Thanks for the reply.  Didn't know using old 0.4.0 naming will break the build. I am closing this issue.
