### ISSUE TITLE
RFC: Create another dir to host Cargo.toml file and directory layout to test/learn examples

### ISSUE THREAD

**Issue by tjyang** [rust-cli/rexpect#83]
Hi @matthiasbeyer 

As a rexpect beginner, I had to create my own  dir structure and file to really run/test/learn rexpect crate.

- Can this be part of rexpect src tree ?
 
```
[me@ipa01 rexpect]$ pwd
/home/me/github/rexpect
[me@ipa01 rexpect]$ tree contrib -L 4
contrib
└── examples
    ├── Cargo.toml
    └── src
        └── bin
            ├── bash_read.rs
            ├── bash.rs
            ├── exit_code.rs
            ├── ftp.rs
            ├── repl.rs
            └── tcp.rs

3 directories, 7 files
[me@ipa01 rexpect]$

```

**Comment by petreeftime** [comment]
You don't need to do this, currently the repo does follow the standard cargo specification. You should be able to run the examples via `cargo run --example example_name`. For example `cargo run --example bash_read`.

**Comment by petreeftime** [comment]
To be honest, the examples aren't super interactive, might be a good idea to add some println message to them to actually prove they're doing anything at all :)

**Comment by tjyang** [comment]
> To be honest, the examples aren't super interactive, might be a good idea to add some println message to them to actually prove they're doing anything at all :)

Thanks for the "cargo run --example example_name", I didn't know there is a --example option. 
more verbose message  will be a good homework  for beginner like me.

**Comment by tjyang** [comment]
Another suggestion is that if "contrib" dir is not part of build process, can you  still add contrib sub-directory to host more advance examples that using ldap3,clap ... crates.
Just a suggestion, if this is not a good idea, please just close this issue.

**Comment by petreeftime** [comment]
I think examples can use [`dev-dependencies`](https://doc.rust-lang.org/rust-by-example/testing/dev_dependencies.html), but cannot check right now. If that's the case, I think it would be fine to add more complex examples using some additional crates that only get compiled for development purposes (although if they're too complex they might not be a good example anymore).

**Comment by tjyang** [comment]
[dev-dependencies](https://doc.rust-lang.org/rust-by-example/testing/dev_dependencies.html) is too deep for me ;)
- My suggestion is to add following dir layout, IF adding contrib directory will not impact the build process. The advance examples can be stored  under contrib/adnvace_examples/src/bin . 

```[me@ipa01 rexpect]$ tree -L 4 contrib
contrib
└── advance_examples
    ├── Cargo.toml
    └── src
        └── bin

3 directories, 1 file
[me@ipa01 rexpect]$

```

**Comment by tjyang** [comment]
Withdraw the suggestion, I created https://github.com/learnrust/rexpect-examples for me to play with.

**Comment by matthiasbeyer** [comment]
>- My suggestion is to add following dir layout, IF adding contrib directory will not impact the build process. The advance examples can be stored under contrib/adnvace_examples/src/bin 

You are always welcome to open up a PR, but honestly I don't see how such a thing would yield any benefit over the existing examples. I don't yet see a proposal for any example code, all I see is that you propose to add more directories... But not how that would enhance the example situation?

**Comment by tjyang** [comment]
Your comment accepted. let me work on a few examples that I think is useful, IMHO.

**Comment by tjyang** [comment]
@matthiasbeyer , [this is the example](https://github.com/learnrust/rexpect-examples/blob/main/src/bin/forumsys_ldap_check.rs) I think is helpful.
